name: afak_tetcher
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+9

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  flutter_localizations:
    sdk: flutter
  flutter_overboard:
  hexcolor:
  flutter_stripe: ^9.2.0
  shared_preferences:
  http:
  bloc:
  flutter_bloc:
  animated_splash_screen: ^1.2.0
  fluttertoast: ^8.0.9
  dio: ^5.1.2
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.12.0
  url_launcher: ^6.1.5
  flutter_local_notifications: ^14.0.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  permission_handler:
  syncfusion_flutter_calendar: ^21.2.10
  device_preview: ^1.1.0
  auto_size_text: ^3.0.0
  lottie:
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.14
  open_filex: ^4.3.2
  cupertino_icons: ^1.0.2
  country_code_picker: ^3.0.0
  pretty_dio_logger: ^1.3.1
  flutter_svg: ^1.1.6
  image_picker:
  internet_connection_checker: ^0.0.1+4
  get_it:
  rxdart: ^0.27.7
  get: ^4.6.5
  retrofit:
  analyzer:
  json_serializable:
  json_annotation:
  dartz:
  freezed:
  cached_network_image:
  shimmer: ^2.0.0
  file_picker: ^5.2.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator:
  build_runner: ^2.1.7


flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/


  fonts:
    - family: Cocon
      fonts:
        - asset: assets/fonts/CoconNextArabic-Light.otf
          weight: 300
        - asset: assets/fonts/CoconNextArabic-Regular.otf
          weight: 400
        - asset: assets/fonts/CoconNextArabic-Bold.otf
          weight: 700

